import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", flag: "🇬🇧", name: "English" },
  { code: "af", flag: "🇿🇦", name: "Afrikaans" },
  { code: "zu", flag: "🇿🇦", name: "Zulu" },
  { code: "xh", flag: "🇿🇦", name: "Xhosa" },
  { code: "st", flag: "🇿🇦", name: "Sotho" },
  { code: "fr", flag: "🇫🇷", name: "French" },
  { code: "de", flag: "🇩🇪", name: "German" },
  { code: "pt", flag: "🇵🇹", name: "Portuguese" },
  { code: "es", flag: "🇪🇸", name: "Spanish" },
  { code: "zh", flag: "🇨🇳", name: "Chinese" },
] as const;

export type LangCode = (typeof LANGUAGES)[number]["code"];

type Translations = Record<string, Record<LangCode, string>>;

const T: Translations = {
  // Nav
  "nav.home": { en: "Home", af: "Tuis", zu: "Ikhaya", xh: "Ikhaya", st: "Lehae", fr: "Accueil", de: "Startseite", pt: "Início", es: "Inicio", zh: "首页" },
  "nav.services": { en: "Services", af: "Dienste", zu: "Izinsiza", xh: "Iinkonzo", st: "Ditshebeletso", fr: "Services", de: "Dienstleistungen", pt: "Serviços", es: "Servicios", zh: "服务" },
  "nav.packages": { en: "Packages", af: "Pakkette", zu: "Amaphakheji", xh: "Iimpahla", st: "Dipakete", fr: "Forfaits", de: "Pakete", pt: "Pacotes", es: "Paquetes", zh: "套餐" },
  "nav.blog": { en: "Blog", af: "Blog", zu: "Blog", xh: "Blog", st: "Blog", fr: "Blog", de: "Blog", pt: "Blog", es: "Blog", zh: "博客" },
  "nav.contact": { en: "Contact", af: "Kontak", zu: "Xhumana", xh: "Qhagamshelana", st: "Ikopanye", fr: "Contact", de: "Kontakt", pt: "Contacto", es: "Contacto", zh: "联系我们" },
  "nav.getStarted": { en: "Get Started", af: "Begin", zu: "Qala", xh: "Qala", st: "Qala", fr: "Commencer", de: "Loslegen", pt: "Começar", es: "Empezar", zh: "开始" },

  // Hero
  "hero.label": { en: "Web Design Agency · South Africa", af: "Webontwerp Agentskap · Suid-Afrika", zu: "I-Ejensi Yokwakha Amawebhu · INingizimu Afrika", xh: "I-Arhente Yoyilo Lwewebhu · UMzantsi Afrika", st: "Setsi sa Moralo oa Marang-rang · Afrika Borwa", fr: "Agence Web · Afrique du Sud", de: "Webdesign Agentur · Südafrika", pt: "Agência Web · África do Sul", es: "Agencia Web · Sudáfrica", zh: "网页设计公司 · 南非" },
  "hero.heading1": { en: "Websites That ", af: "Webtuiste Wat ", zu: "Amawebhusayithi ", xh: "Iwebhsayithi ", st: "Diasaete tse ", fr: "Des Sites Web Qui ", de: "Websites Die ", pt: "Sites Web Que ", es: "Sitios Web Que ", zh: "助力您的" },
  "hero.heading2": { en: "Grow Your Business", af: "U Besigheid Laat Groei", zu: "Akhulisa Ibhizinisi Lakho", xh: "Ezikhulisa Ishishini Lakho", st: "Kgolohang Kgwebo ya Hao", fr: "Font Grandir Votre Entreprise", de: "Ihr Unternehmen Wachsen Lassen", pt: "Fazem Crescer o Seu Negócio", es: "Hacen Crecer Tu Negocio", zh: "业务增长的网站" },
  "hero.sub": {
    en: "We build modern, mobile-friendly websites for South African businesses — designed to get you found, trusted, and thriving online. Packages from R5,500.",
    af: "Ons bou moderne, mobielvriendelike webtuiste vir Suid-Afrikaanse besighede — ontwerp om u aanlyn gevind, vertrou en floreer te word. Pakkette vanaf R5,500.",
    zu: "Sakha amawebhusayithi asamodern, afanele izikhali zeselula amabhizinisi aseNingizimu Afrika. Amaphakheji kusuka ku-R5,500.",
    xh: "Sakha iiwebhsayithi zanamhlanje, ezilungele iiselfowuni zamashishini aseMzantsi Afrika. Iimpahla ukusuka kwi-R5,500.",
    st: "Re aha diasaete tsa sejoale-joale, tse loketseng mehala bakeng sa likgwebo tsa Afrika Borwa. Dipakete ho tloha ho R5,500.",
    fr: "Nous créons des sites web modernes et adaptés aux mobiles pour les entreprises sud-africaines — conçus pour vous faire trouver, faire confiance et prospérer en ligne. Forfaits à partir de R5 500.",
    de: "Wir erstellen moderne, mobilfreundliche Websites für südafrikanische Unternehmen — damit Sie online gefunden werden, Vertrauen aufbauen und erfolgreich sind. Pakete ab R5.500.",
    pt: "Criamos sites modernos e compatíveis com dispositivos móveis para empresas sul-africanas — projetados para que você seja encontrado, confiável e próspero online. Pacotes a partir de R5.500.",
    es: "Creamos sitios web modernos y compatibles con móviles para empresas sudafricanas — diseñados para que te encuentren, confíen en ti y prosperes en línea. Paquetes desde R5.500.",
    zh: "我们为南非企业打造现代化、移动端友好的网站——帮助您在网上被发现、获得信任并蓬勃发展。套餐起价R5,500。",
  },
  "hero.viewPackages": { en: "View Packages", af: "Bekyk Pakkette", zu: "Buka Amaphakheji", xh: "Jonga Iimpahla", st: "Sheba Dipakete", fr: "Voir les Forfaits", de: "Pakete Ansehen", pt: "Ver Pacotes", es: "Ver Paquetes", zh: "查看套餐" },
  "hero.ourServices": { en: "Our Services", af: "Ons Dienste", zu: "Izinsiza Zethu", xh: "Iinkonzo Zethu", st: "Ditshebeletso Tsa Rona", fr: "Nos Services", de: "Unsere Dienstleistungen", pt: "Nossos Serviços", es: "Nuestros Servicios", zh: "我们的服务" },

  // Stats
  "stats.turnaround": { en: "Average Turnaround", af: "Gemiddelde Omlooptyd", zu: "Isikhathi Esijwayelekile", xh: "Ixesha Eliqhelekileyo", st: "Nako e Tlwaelehileng", fr: "Délai Moyen", de: "Durchschnittliche Lieferzeit", pt: "Prazo Médio", es: "Plazo Promedio", zh: "平均周转时间" },
  "stats.packagesFrom": { en: "Packages From", af: "Pakkette Vanaf", zu: "Amaphakheji Kusuka", xh: "Iimpahla Ukusuka", st: "Dipakete Ho Tloha", fr: "Forfaits à partir de", de: "Pakete Ab", pt: "Pacotes A Partir De", es: "Paquetes Desde", zh: "套餐起价" },
  "stats.hiddenFees": { en: "Hidden Fees", af: "Verborge Fooie", zu: "Izindleko Ezifihliwe", xh: "Iintlawulo Ezifihliweyo", st: "Ditjeo Tse Patilweng", fr: "Frais Cachés", de: "Versteckte Gebühren", pt: "Taxas Ocultas", es: "Tarifas Ocultas", zh: "隐藏费用" },
  "stats.performance": { en: "Performance", af: "Werkverrigting", zu: "Ukusebenza", xh: "Ukusebenza", st: "Tshebetso", fr: "Performance", de: "Leistung", pt: "Performance", es: "Rendimiento", zh: "性能" },
  "stats.accessibility": { en: "Accessibility", af: "Toeganklikheid", zu: "Ukufinyelela", xh: "Ukufikelela", st: "Phihlello", fr: "Accessibilité", de: "Barrierefreiheit", pt: "Acessibilidade", es: "Accesibilidad", zh: "可访问性" },
  "stats.bestPractices": { en: "Best Practices", af: "Beste Praktyke", zu: "Izindlela Ezinhle", xh: "Iindlela Ezilungileyo", st: "Mekhoa e Metle", fr: "Bonnes Pratiques", de: "Best Practices", pt: "Melhores Práticas", es: "Mejores Prácticas", zh: "最佳实践" },

  // Why section
  "why.heading": { en: "Everything You Need to Succeed Online", af: "Alles Wat U Nodig Het Om Aanlyn Te Slaag", zu: "Konke Okudingayo Ukuphumelela Ku-inthanethi", xh: "Yonke Into Oyidingayo Ukuphumelela Kwi-intanethi", st: "Tsohle Tseo O Li Hlokang Ho Atleha Inthaneteng", fr: "Tout Ce Dont Vous Avez Besoin Pour Réussir En Ligne", de: "Alles Was Sie Brauchen Um Online Erfolgreich Zu Sein", pt: "Tudo O Que Você Precisa Para Ter Sucesso Online", es: "Todo Lo Que Necesitas Para Triunfar Online", zh: "在线成功所需的一切" },
  "why.sub": { en: "We combine sharp design with technical expertise to build websites that actually work for your business.", af: "Ons kombineer skerp ontwerp met tegniese kundigheid om webtuiste te bou wat werklik vir u besigheid werk.", zu: "Sihlanganisa ukwakhiwa okuhle nobuchwepheshe ukwakha amawebhusayithi asebenzela ibhizinisi lakho.", xh: "Sidibanisa uyilo olubukhali nobuchule bobuchwepheshe ukwakha iiwebhsayithi ezisebenzela ishishini lakho.", st: "Re kopanya moralo o bohale le tsebo ea thekenoloji ho aha diasaete tse sebetsang hantle bakeng sa kgwebo ea hau.", fr: "Nous combinons un design percutant avec une expertise technique pour créer des sites qui fonctionnent réellement pour votre entreprise.", de: "Wir kombinieren scharfes Design mit technischer Expertise, um Websites zu erstellen, die wirklich für Ihr Unternehmen funktionieren.", pt: "Combinamos design afiado com expertise técnica para construir sites que realmente funcionam para o seu negócio.", es: "Combinamos diseño afilado con experiencia técnica para crear sitios web que realmente funcionen para tu negocio.", zh: "我们将精锐的设计与技术专长相结合，打造真正为您的业务服务的网站。" },
  "why.customDesign": { en: "Custom Design", af: "Pasgemaakte Ontwerp", zu: "Ukwakhiwa Okukhethekile", xh: "Uyilo Olwenzelwe", st: "Moralo o Ikgethileng", fr: "Design Sur Mesure", de: "Individuelles Design", pt: "Design Personalizado", es: "Diseño Personalizado", zh: "定制设计" },
  "why.customDesignDesc": { en: "No templates. Every site is designed from scratch to reflect your brand uniquely.", af: "Geen sjablone nie. Elke webtuiste word van nuuts af ontwerp om u handelsmerk uniek te weerspieël.", zu: "Akukho amathemplethi. Isayithi ngayinye yakhiwa kabusha ukubonisa umkhiqizo wakho ngokukhethekile.", xh: "Akukho zitempleti. Isayithi nganye iyilwe ukusuka ekuqaleni ukubonisa umkhankaso wakho ngendlela eyodwa.", st: "Ha ho li-template. Saete e 'ngoe le e' ngoe e etselitsoe ho tloha qalong ho bonts'a brand ea hau ka mokhoa o ikgethileng.", fr: "Pas de modèles. Chaque site est conçu de zéro pour refléter votre marque de manière unique.", de: "Keine Vorlagen. Jede Seite wird von Grund auf neu gestaltet, um Ihre Marke einzigartig widerzuspiegeln.", pt: "Sem templates. Cada site é desenhado do zero para refletir a sua marca de forma única.", es: "Sin plantillas. Cada sitio se diseña desde cero para reflejar tu marca de manera única.", zh: "没有模板。每个网站都从零开始设计，独特地反映您的品牌。" },
  "why.lightningFast": { en: "Lightning Fast", af: "Blitsvinnig", zu: "Kusheshe Kakhulu", xh: "Kukhawuleza Kakhulu", st: "Potlako Haholo", fr: "Ultra Rapide", de: "Blitzschnell", pt: "Ultra Rápido", es: "Ultra Rápido", zh: "闪电般快速" },
  "why.lightningFastDesc": { en: "Optimised for speed so visitors stay and Google ranks you higher.", af: "Geoptimaliseer vir spoed sodat besoekers bly en Google u hoër rangeer.", zu: "Kwenziwe ukuba kusheshe ukuze abavakashi bahlale futhi i-Google ikukhombise phezulu.", xh: "Yenzelwe ukukhawuleza ukuze abatyeleli bahlale kwaye i-Google ikubeke phezulu.", st: "E lokiselitsoe lebelo hore baeti ba lule mme Google e u behele holimo.", fr: "Optimisé pour la vitesse afin que les visiteurs restent et que Google vous classe plus haut.", de: "Optimiert für Geschwindigkeit, damit Besucher bleiben und Google Sie höher einstuft.", pt: "Otimizado para velocidade para que os visitantes fiquem e o Google o posicione melhor.", es: "Optimizado para velocidad para que los visitantes se queden y Google te posicione mejor.", zh: "优化速度，让访客留下，让Google给您更高排名。" },
  "why.mobileFirst": { en: "Mobile First", af: "Mobiel Eerste", zu: "Iselula Kuqala", xh: "Ifowuni Kuqala", st: "Mohala Pele", fr: "Mobile First", de: "Mobile First", pt: "Mobile First", es: "Mobile First", zh: "移动优先" },
  "why.mobileFirstDesc": { en: "Perfect on every screen — phone, tablet, desktop — always.", af: "Perfek op elke skerm — foon, tablet, rekenaar — altyd.", zu: "Kuphelele kuzo zonke izinhlelo — ucingo, ithebhulethi, ikhompyutha — njalo.", xh: "Igqibelele kwisikrini ngasinye — ifowuni, ithebhlethi, ideskhophu — ngalo lonke ixesha.", st: "E phethahetseng skrining e 'ngoe le e' ngoe — mohala, theblete, desktop — kamehla.", fr: "Parfait sur chaque écran — téléphone, tablette, ordinateur — toujours.", de: "Perfekt auf jedem Bildschirm — Handy, Tablet, Desktop — immer.", pt: "Perfeito em cada ecrã — telemóvel, tablet, desktop — sempre.", es: "Perfecto en cada pantalla — teléfono, tableta, escritorio — siempre.", zh: "在每个屏幕上都完美——手机、平板、桌面——始终如此。" },
  "why.seoReady": { en: "SEO Ready", af: "SEO Gereed", zu: "I-SEO Ilungile", xh: "I-SEO Ilungile", st: "SEO e Lokile", fr: "Prêt pour le SEO", de: "SEO-Bereit", pt: "Pronto para SEO", es: "Listo para SEO", zh: "SEO就绪" },
  "why.seoReadyDesc": { en: "Built with search engines in mind so customers can actually find you.", af: "Gebou met soekenjins in gedagte sodat kliënte u werklik kan vind.", zu: "Kwakhiwe ngokucabangela izinjini zokusesha ukuze amakhasimende akuthole.", xh: "Yakhiwe ngokucinga ngeenjini zokukhangela ukuze abathengi bakufumane.", st: "E ahiloe ka ho nahana ka li-engine tsa ho batla hore bareki ba tle ba o fumane.", fr: "Conçu pour les moteurs de recherche afin que les clients puissent réellement vous trouver.", de: "Mit Suchmaschinen im Sinn gebaut, damit Kunden Sie tatsächlich finden können.", pt: "Construído com motores de busca em mente para que os clientes o possam encontrar.", es: "Construido pensando en los motores de búsqueda para que los clientes realmente te encuentren.", zh: "以搜索引擎为核心构建，让客户能够真正找到您。" },
  "why.secure": { en: "Secure & Reliable", af: "Veilig & Betroubaar", zu: "Kuphephile & Kuthembekile", xh: "Kukhuselekile & Kuthembakele", st: "E Bolokehileng & E Tšepahalang", fr: "Sécurisé & Fiable", de: "Sicher & Zuverlässig", pt: "Seguro & Confiável", es: "Seguro & Confiable", zh: "安全可靠" },
  "why.secureDesc": { en: "SSL, regular backups, and security updates handled for you.", af: "SSL, gereelde rugsteun en sekuriteitsopdaterings word vir u hanteer.", zu: "I-SSL, ukusekelwa okuvamile, nezibuyekezo zokuphepha zihlelwa ngawe.", xh: "I-SSL, iibhekap eziqhelekileyo, kunye nohlaziyo lwezokhuseleko ziyenzelwa.", st: "SSL, li-backup tse tloaelehileng, le ntlafatso tsa ts'ireletso li etsetsoa uena.", fr: "SSL, sauvegardes régulières et mises à jour de sécurité gérées pour vous.", de: "SSL, regelmäßige Backups und Sicherheitsupdates werden für Sie erledigt.", pt: "SSL, backups regulares e atualizações de segurança tratados para si.", es: "SSL, copias de seguridad regulares y actualizaciones de seguridad gestionadas para ti.", zh: "SSL、定期备份和安全更新为您处理。" },
  "why.whatsapp": { en: "WhatsApp & Maps", af: "WhatsApp & Kaarte", zu: "WhatsApp & Amamephu", xh: "WhatsApp & Iimephu", st: "WhatsApp & Limmepe", fr: "WhatsApp & Maps", de: "WhatsApp & Maps", pt: "WhatsApp & Maps", es: "WhatsApp & Maps", zh: "WhatsApp和地图" },
  "why.whatsappDesc": { en: "We integrate WhatsApp chat and Google Maps so customers can reach you instantly.", af: "Ons integreer WhatsApp-klets en Google Maps sodat kliënte u onmiddellik kan bereik.", zu: "Sifaka i-WhatsApp chat ne-Google Maps ukuze amakhasimende akufinyelele ngokushesha.", xh: "Sifaka i-WhatsApp chat ne-Google Maps ukuze abathengi bakufikelele ngokukhawuleza.", st: "Re kenyelletsa WhatsApp chat le Google Maps hore bareki ba o fihlele kapele.", fr: "Nous intégrons WhatsApp et Google Maps pour que les clients puissent vous joindre instantanément.", de: "Wir integrieren WhatsApp-Chat und Google Maps, damit Kunden Sie sofort erreichen können.", pt: "Integramos WhatsApp e Google Maps para que os clientes o possam contactar instantaneamente.", es: "Integramos WhatsApp y Google Maps para que los clientes puedan contactarte al instante.", zh: "我们集成WhatsApp聊天和Google地图，让客户可以即时联系您。" },

  // How it works
  "how.heading": { en: "Simple 4-Step Process", af: "Eenvoudige 4-Stap Proses", zu: "Inqubo Elula Yezinyathelo Ezine", xh: "Inkqubo Elula Yamanyathelo Amane", st: "Ts'ebetso E Bonolo ea Mehato e Mene", fr: "Un Processus Simple en 4 Étapes", de: "Einfacher 4-Schritte-Prozess", pt: "Processo Simples em 4 Passos", es: "Proceso Simple de 4 Pasos", zh: "简单的4步流程" },
  "how.discovery": { en: "Discovery", af: "Ontdekking", zu: "Ukuthola", xh: "Ukufumanisa", st: "Tlhahlobo", fr: "Découverte", de: "Entdeckung", pt: "Descoberta", es: "Descubrimiento", zh: "发现" },
  "how.discoveryDesc": { en: "We learn about your business, goals, and target audience.", af: "Ons leer oor u besigheid, doelwitte en teikengehoor.", zu: "Sifunda ngebhizinisi lakho, izinjongo, kanye nabathengi obahloselayo.", xh: "Sifunda ngeshishini lakho, iinjongo, kunye nabathengi obajolisayo.", st: "Re ithuta ka kgwebo ea hau, lipakane, le bamameli bao o ba shebileng.", fr: "Nous apprenons à connaître votre entreprise, vos objectifs et votre public cible.", de: "Wir lernen Ihr Unternehmen, Ihre Ziele und Ihre Zielgruppe kennen.", pt: "Aprendemos sobre o seu negócio, objetivos e público-alvo.", es: "Aprendemos sobre tu negocio, objetivos y público objetivo.", zh: "了解您的业务、目标和目标受众。" },
  "how.design": { en: "Design", af: "Ontwerp", zu: "Ukwakha", xh: "Uyilo", st: "Moralo", fr: "Design", de: "Design", pt: "Design", es: "Diseño", zh: "设计" },
  "how.designDesc": { en: "We create a stunning design tailored to your brand and customers.", af: "Ons skep 'n pragtige ontwerp wat by u handelsmerk en kliënte pas.", zu: "Senza umklamo omuhle owenzelwe umkhiqizo wakho namakhasimende.", xh: "Senza uyilo oluhle olwenzelwe umkhankaso wakho nabathengi.", st: "Re etsa moralo o motle o lokisetsoeng brand ea hau le bareki.", fr: "Nous créons un design époustouflant adapté à votre marque et vos clients.", de: "Wir erstellen ein atemberaubendes Design, das auf Ihre Marke und Kunden zugeschnitten ist.", pt: "Criamos um design impressionante adaptado à sua marca e clientes.", es: "Creamos un diseño impresionante adaptado a tu marca y clientes.", zh: "我们创建针对您的品牌和客户量身定制的精美设计。" },
  "how.build": { en: "Build", af: "Bou", zu: "Ukwakha", xh: "Ukwakha", st: "Ho Aha", fr: "Développement", de: "Entwicklung", pt: "Desenvolvimento", es: "Desarrollo", zh: "构建" },
  "how.buildDesc": { en: "We develop and test your site to be fast, secure, and pixel-perfect.", af: "Ons ontwikkel en toets u webtuiste om vinnig, veilig en pixelperfek te wees.", zu: "Senza futhi sihlole isayithi lakho ukuba lisheshe, liphephe, futhi liphelele.", xh: "Siphuhlisa kwaye sivavanya isayithi yakho ukuba ikhawuleze, ikhuseleke, kwaye igqibeleleyo.", st: "Re nts'etsapele le ho lekola saete ea hau hore e be potlako, e bolokehileng, le e phethahetseng.", fr: "Nous développons et testons votre site pour qu'il soit rapide, sécurisé et pixel-parfait.", de: "Wir entwickeln und testen Ihre Website, damit sie schnell, sicher und pixelgenau ist.", pt: "Desenvolvemos e testamos o seu site para que seja rápido, seguro e perfeito ao pixel.", es: "Desarrollamos y probamos tu sitio para que sea rápido, seguro y perfecto al pixel.", zh: "我们开发和测试您的网站，使其快速、安全且像素完美。" },
  "how.launch": { en: "Launch", af: "Lanseer", zu: "Ukuqala", xh: "Ukuqalisa", st: "Ho Qala", fr: "Lancement", de: "Start", pt: "Lançamento", es: "Lanzamiento", zh: "上线" },
  "how.launchDesc": { en: "We go live and provide ongoing support to keep everything running.", af: "Ons gaan lewendig en bied deurlopende ondersteuning om alles aan die gang te hou.", zu: "Siqala futhi sinikeza usizo oluqhubekayo ukugcina konke kusebenza.", xh: "Siqalisa kwaye sinikeze inkxaso eqhubekayo ukugcina yonke into isebenza.", st: "Re qala mme re fana ka ts'ehetso e tsoelang pele ho boloka ntho tsohle li tsamaea.", fr: "Nous lançons et fournissons un support continu pour que tout fonctionne.", de: "Wir gehen live und bieten fortlaufende Unterstützung, damit alles reibungslos läuft.", pt: "Lançamos e fornecemos suporte contínuo para manter tudo funcionando.", es: "Lanzamos y proporcionamos soporte continuo para mantener todo funcionando.", zh: "我们上线并提供持续支持以保持一切运行。" },

  // CTA
  "cta.ready": { en: "Ready to elevate your online presence?", af: "Gereed om u aanlyn teenwoordigheid te verhef?", zu: "Ulungele ukukhulisa ukuba khona kwakho ku-inthanethi?", xh: "Ulungile ukuphakamisa ubukho bakho kwi-intanethi?", st: "U lokile ho phahamisa boteng ba hau inthaneteng?", fr: "Prêt à élever votre présence en ligne?", de: "Bereit, Ihre Online-Präsenz zu erhöhen?", pt: "Pronto para elevar a sua presença online?", es: "¿Listo para elevar tu presencia online?", zh: "准备好提升您的在线形象了吗？" },
  "cta.readySub": { en: "Let's build something great together. We'll have your new website live within 2 weeks — guaranteed.", af: "Kom ons bou saam iets groots. U nuwe webtuiste sal binne 2 weke lewendig wees — gewaarborg.", zu: "Masiakhe okuhle ndawonye. Iwebhusayithi yakho entsha izoba bukhoma phakathi nezinsuku ezingu-2 — siyaqinisekisa.", xh: "Masakheni into entle kunye. Iwebhsayithi yakho entsha iya kuba bukhoma ngaphakathi kweeveki ezi-2 — siyaqinisekisa.", st: "Ha re aheng ntho e ntle mmoho. Saete ea hau e ntjha e tla ba teng ka hare ho libeke tse 2 — re netefatsa.", fr: "Construisons quelque chose de génial ensemble. Votre nouveau site sera en ligne en 2 semaines — garanti.", de: "Lassen Sie uns zusammen etwas Großartiges bauen. Ihre neue Website wird innerhalb von 2 Wochen live sein — garantiert.", pt: "Vamos construir algo incrível juntos. O seu novo site estará online em 2 semanas — garantido.", es: "Construyamos algo genial juntos. Tu nuevo sitio web estará en línea en 2 semanas — garantizado.", zh: "让我们一起打造伟大的东西。您的新网站将在2周内上线——保证。" },
  "cta.contactUs": { en: "Contact Us Today", af: "Kontak Ons Vandag", zu: "Xhumana Nathi Namuhla", xh: "Qhagamshelana Nathi Namhlanje", st: "Ikopanye Le Rona Kajeno", fr: "Contactez-nous Aujourd'hui", de: "Kontaktieren Sie Uns Heute", pt: "Contacte-nos Hoje", es: "Contáctanos Hoy", zh: "今天联系我们" },

  // Services page
  "services.heading": { en: "What We ", af: "Wat Ons ", zu: "Esiku", xh: "Esiku", st: "Seo Re Se", fr: "Ce Que Nous ", de: "Was Wir ", pt: "O Que ", es: "Lo Que ", zh: "我们" },
  "services.heading2": { en: "Offer", af: "Bied", zu: "nikezayo", xh: "nikezayo", st: "Fanang", fr: "Offrons", de: "Bieten", pt: "Oferecemos", es: "Ofrecemos", zh: "提供" },
  "services.sub": { en: "Modern websites that work — designed, built, and maintained by Elevate Digitals.", af: "Moderne webtuiste wat werk — ontwerp, gebou en onderhou deur Elevate Digitals.", zu: "Amawebhusayithi asamodern asebenzayo — akhiwe, akhiwe, futhi agcinwa yi-Elevate Digitals.", xh: "Iiwebhsayithi zanamhlanje ezisebenzayo — eziyilwe, ezakhiwe, kwaye zigcinwe yi-Elevate Digitals.", st: "Diasaete tsa sejoale-joale tse sebetsang — tse entsoeng, tse ahilweng, le tse bolokwang ke Elevate Digitals.", fr: "Des sites web modernes qui fonctionnent — conçus, développés et maintenus par Elevate Digitals.", de: "Moderne Websites, die funktionieren — entworfen, gebaut und gewartet von Elevate Digitals.", pt: "Sites modernos que funcionam — projetados, construídos e mantidos pela Elevate Digitals.", es: "Sitios web modernos que funcionan — diseñados, construidos y mantenidos por Elevate Digitals.", zh: "现代化且有效的网站——由Elevate Digitals设计、构建和维护。" },
  "services.notSure": { en: "Not sure what you need?", af: "Nie seker wat u nodig het nie?", zu: "Awuqiniseki ukuthi udingani?", xh: "Awuqinisekanga ukuba ufuna ntoni?", st: "Ha u na bonnete ba seo u se hlokang?", fr: "Vous ne savez pas ce dont vous avez besoin?", de: "Nicht sicher, was Sie brauchen?", pt: "Não tem a certeza do que precisa?", es: "¿No estás seguro de lo que necesitas?", zh: "不确定您需要什么？" },
  "services.letsChat": { en: "Let's chat — we'll figure it out together.", af: "Kom ons praat — ons sal dit saam uitwerk.", zu: "Masikhulume — sizokusebenza ndawonye.", xh: "Masincokole — siza kuyisombulula kunye.", st: "Ha re buisane — re tla e sebetsa mmoho.", fr: "Discutons — nous trouverons ensemble.", de: "Lassen Sie uns reden — wir finden es gemeinsam heraus.", pt: "Vamos conversar — vamos descobrir juntos.", es: "Hablemos — lo resolveremos juntos.", zh: "让我们聊聊——我们一起来解决。" },
  "services.freeQuote": { en: "Get a Free Quote", af: "Kry 'n Gratis Kwotasie", zu: "Thola Isicelo Simahala", xh: "Fumana Isicelo Simahla", st: "Fumana Quota e Mahala", fr: "Obtenir un Devis Gratuit", de: "Kostenloses Angebot", pt: "Obter Orçamento Gratuito", es: "Obtener Presupuesto Gratuito", zh: "获取免费报价" },

  // Packages page
  "packages.heading": { en: "Transparent ", af: "Deursigtige ", zu: "Amaphakheji ", xh: "Iimpahla ", st: "Dipakete Tse ", fr: "Forfaits ", de: "Transparente ", pt: "Pacotes ", es: "Paquetes ", zh: "透明" },
  "packages.heading2": { en: "Packages", af: "Pakkette", zu: "Asobala", xh: "Ezicacileyo", st: "Hlakileng", fr: "Transparents", de: "Pakete", pt: "Transparentes", es: "Transparentes", zh: "套餐" },
  "packages.sub": { en: "No hidden fees. No surprises. Just honest pricing for great work. All prices in ZAR.", af: "Geen verborge fooie nie. Geen verrassings nie. Net eerlike pryse vir goeie werk. Alle pryse in ZAR.", zu: "Akukho izindleko ezifihliwe. Akukho okumangalisayo. Amanani aqotho omsebenzi omuhle kuphela. Konke nge-ZAR.", xh: "Akukho ntlawulo zifihliweyo. Akukho mammangaliso. Amaxabiso anyanisekileyo kuphela omsebenzi omhle. Konke nge-ZAR.", st: "Ha ho ditjeo tse patilweng. Ha ho makalo. Litheko tse tsepameng feela bakeng sa mosebetsi o motle. Theko tsohle ka ZAR.", fr: "Pas de frais cachés. Pas de surprises. Juste des prix honnêtes pour un excellent travail. Tous les prix en ZAR.", de: "Keine versteckten Gebühren. Keine Überraschungen. Nur ehrliche Preise für großartige Arbeit. Alle Preise in ZAR.", pt: "Sem taxas ocultas. Sem surpresas. Apenas preços honestos para um ótimo trabalho. Todos os preços em ZAR.", es: "Sin tarifas ocultas. Sin sorpresas. Solo precios honestos por un gran trabajo. Todos los precios en ZAR.", zh: "没有隐藏费用。没有意外。只有诚实的定价。所有价格以ZAR计。" },
  "packages.onceOff": { en: "once-off", af: "eenmalig", zu: "kanye kuphela", xh: "kanye kuphela", st: "hang le hang", fr: "unique", de: "einmalig", pt: "pagamento único", es: "pago único", zh: "一次性" },
  "packages.mostPopular": { en: "Most Popular", af: "Mees Gewild", zu: "Idumile Kakhulu", xh: "Iyathandwa Kakhulu", st: "E Ratwa Haholo", fr: "Le Plus Populaire", de: "Am Beliebtesten", pt: "Mais Popular", es: "Más Popular", zh: "最受欢迎" },
  "packages.recommended": { en: "Recommended", af: "Aanbeveel", zu: "Enconyiwe", xh: "Ecetyiswayo", st: "E Khothaletswang", fr: "Recommandé", de: "Empfohlen", pt: "Recomendado", es: "Recomendado", zh: "推荐" },
  "packages.letsTalk": { en: "Let's Talk", af: "Kom Ons Praat", zu: "Masikhulume", xh: "Masincokole", st: "Ha Re Buisane", fr: "Parlons", de: "Lass uns reden", pt: "Vamos Conversar", es: "Hablemos", zh: "联系我们" },
  "packages.maintenance": { en: "Monthly Maintenance Plans", af: "Maandelikse Onderhoudplanne", zu: "Izinhlelo Zokugcina Zenyanga", xh: "Iiplani Zokuondla Zenyanga", st: "Merero ea Tlhokomelo ea Khoeli", fr: "Plans de Maintenance Mensuelle", de: "Monatliche Wartungspläne", pt: "Planos de Manutenção Mensal", es: "Planes de Mantenimiento Mensual", zh: "月度维护计划" },
  "packages.maintenanceSub": { en: "Keep your site fast, secure, and up to date.", af: "Hou u webtuiste vinnig, veilig en op datum.", zu: "Gcina isayithi lakho lisheshe, liphephe, futhi libuyekeziwe.", xh: "Gcina isayithi yakho ikhawuleza, ikhuselekile, kwaye ihlaziyiwe.", st: "Boloka saete ea hau e le potlako, e bolokehileng, le e ntjhafaditsweng.", fr: "Gardez votre site rapide, sécurisé et à jour.", de: "Halten Sie Ihre Website schnell, sicher und aktuell.", pt: "Mantenha o seu site rápido, seguro e atualizado.", es: "Mantén tu sitio rápido, seguro y actualizado.", zh: "保持您的网站快速、安全和最新。" },
  "packages.customNeed": { en: "Need something custom?", af: "Iets pasgemaaks nodig?", zu: "Udinga okwenzelwe wena?", xh: "Udinga into eyenzelweyo?", st: "Hloka ntho e ikgethileng?", fr: "Besoin de quelque chose sur mesure?", de: "Brauchen Sie etwas Individuelles?", pt: "Precisa de algo personalizado?", es: "¿Necesitas algo personalizado?", zh: "需要定制服务？" },
  "packages.flexible": { en: "We're flexible — let's talk.", af: "Ons is buigsaam — kom ons praat.", zu: "Siyaguquguquka — masikhulume.", xh: "Siyaguquguquka — masincokole.", st: "Re a fetofetohana — ha re buisane.", fr: "Nous sommes flexibles — parlons.", de: "Wir sind flexibel — lassen Sie uns reden.", pt: "Somos flexíveis — vamos conversar.", es: "Somos flexibles — hablemos.", zh: "我们很灵活——让我们谈谈。" },
  "packages.customQuote": { en: "Get a Custom Quote", af: "Kry 'n Pasgemaakte Kwotasie", zu: "Thola Isicelo Esakhiwe Ngokwakho", xh: "Fumana Isicelo Esenzelwe Wena", st: "Fumana Quota e Ikgethileng", fr: "Obtenir un Devis Personnalisé", de: "Individuelles Angebot Anfordern", pt: "Obter Orçamento Personalizado", es: "Obtener Presupuesto Personalizado", zh: "获取定制报价" },

  // Blog page
  "blog.heading": { en: "The Elevate ", af: "Die Elevate ", zu: "I-Elevate ", xh: "I-Elevate ", st: "Elevate ", fr: "Le ", de: "Der Elevate ", pt: "O ", es: "El ", zh: "Elevate " },
  "blog.heading2": { en: "Blog", af: "Blog", zu: "Blog", xh: "Blog", st: "Blog", fr: "Blog Elevate", de: "Blog", pt: "Blog Elevate", es: "Blog Elevate", zh: "博客" },
  "blog.sub": { en: "Practical advice to help South African businesses grow online — web design, SEO, and digital marketing tips you can actually use.", af: "Praktiese raad om Suid-Afrikaanse besighede te help om aanlyn te groei — webontwerp, SEO en digitale bemarkingswenke wat u werklik kan gebruik.", zu: "Izeluleko ezisebenzayo zokusiza amabhizinisi aseNingizimu Afrika akhule ku-inthanethi.", xh: "Iingcebiso ezisebenzayo zokunceda amashishini aseMzantsi Afrika akhule kwi-intanethi.", st: "Likeletso tse sebetsang ho thusa likgwebo tsa Afrika Borwa ho hola inthaneteng.", fr: "Des conseils pratiques pour aider les entreprises sud-africaines à se développer en ligne.", de: "Praktische Tipps, um südafrikanischen Unternehmen zu helfen, online zu wachsen.", pt: "Conselhos práticos para ajudar as empresas sul-africanas a crescer online.", es: "Consejos prácticos para ayudar a las empresas sudafricanas a crecer online.", zh: "帮助南非企业在线成长的实用建议。" },
  "blog.readMore": { en: "Read more", af: "Lees meer", zu: "Funda kabanzi", xh: "Funda ngaphezulu", st: "Bala haholoanyane", fr: "Lire la suite", de: "Mehr lesen", pt: "Leia mais", es: "Leer más", zh: "阅读更多" },
  "blog.comingSoon": { en: "Coming soon", af: "Binnekort", zu: "Kuyeza maduze", xh: "Iyeza kungekudala", st: "E tla haufi", fr: "Bientôt", de: "Demnächst", pt: "Em breve", es: "Próximamente", zh: "即将推出" },

  // Contact page
  "contact.heading1": { en: "Let's Start Your ", af: "Kom Ons Begin U ", zu: "Masiqale ", xh: "Masiqale ", st: "Ha Re Qale ", fr: "Commençons Votre ", de: "Lassen Sie Uns Ihr ", pt: "Vamos Começar O Seu ", es: "Comencemos Tu ", zh: "让我们开始您的" },
  "contact.heading2": { en: "Project", af: "Projek", zu: "Iphrojekthi Yakho", xh: "Iphrojekthi Yakho", st: "Projeke ea Hau", fr: "Projet", de: "Projekt Beginnen", pt: "Projeto", es: "Proyecto", zh: "项目" },
  "contact.sub": { en: "Fill in the form and we'll get back to you within 24 hours with a free consultation and quote. No pressure, no jargon — just a friendly chat.", af: "Vul die vorm in en ons sal binne 24 uur met 'n gratis konsultasie en kwotasie na u terugkom. Geen druk, geen jargon — net 'n vriendelike geselsie.", zu: "Gcwalisa ifomu futhi sizokuphendula phakathi namahora angu-24 ngokubonisana kwamahhala nesicelo. Akukho ngcindezi — kukhuluma nje.", xh: "Gcwalisa ifomu kwaye siza kuphendula ngaphakathi kweeyure ezingama-24 ngobonisano lwasimahla nesicelo. Akukho mxinwa — incoko enobuhlobo nje.", st: "Tlatsa foromo mme re tla u kgutlisa ka hare ho dihora tse 24 ka keletso e mahala le quota. Ha ho kgothallo — puisano e mosa feela.", fr: "Remplissez le formulaire et nous vous répondrons sous 24 heures avec une consultation et un devis gratuits. Sans pression, sans jargon — juste une discussion amicale.", de: "Füllen Sie das Formular aus und wir melden uns innerhalb von 24 Stunden mit einer kostenlosen Beratung und einem Angebot. Kein Druck, kein Fachjargon — nur ein freundliches Gespräch.", pt: "Preencha o formulário e entraremos em contacto dentro de 24 horas com uma consulta e orçamento gratuitos. Sem pressão, sem jargão — apenas uma conversa amigável.", es: "Rellena el formulario y nos pondremos en contacto contigo en 24 horas con una consulta y presupuesto gratuitos. Sin presión, sin jerga — solo una charla amigable.", zh: "填写表格，我们将在24小时内回复您，提供免费咨询和报价。没有压力，没有术语——只是友好的聊天。" },
  "contact.email": { en: "Email", af: "E-pos", zu: "I-imeyili", xh: "I-imeyile", st: "Imeile", fr: "E-mail", de: "E-Mail", pt: "E-mail", es: "Correo", zh: "电子邮件" },
  "contact.whatsapp": { en: "WhatsApp / Phone", af: "WhatsApp / Foon", zu: "WhatsApp / Ucingo", xh: "WhatsApp / Ifowuni", st: "WhatsApp / Mohala", fr: "WhatsApp / Téléphone", de: "WhatsApp / Telefon", pt: "WhatsApp / Telefone", es: "WhatsApp / Teléfono", zh: "WhatsApp / 电话" },
  "contact.website": { en: "Website", af: "Webwerf", zu: "Iwebhusayithi", xh: "Iwebhsayithi", st: "Saete", fr: "Site Web", de: "Webseite", pt: "Website", es: "Sitio Web", zh: "网站" },
  "contact.hours": { en: "Business Hours", af: "Besigheidsure", zu: "Amahora Ebhizinisi", xh: "Amaxesha Omsebenzi", st: "Diura tsa Kgwebo", fr: "Heures d'Ouverture", de: "Geschäftszeiten", pt: "Horário de Funcionamento", es: "Horario de Atención", zh: "营业时间" },
  "contact.monFri": { en: "Mon–Fri: 07:00–19:00", af: "Maan–Vry: 07:00–19:00", zu: "Msombuluko–Lwesihlanu: 07:00–19:00", xh: "Mvulo–Lwesihlanu: 07:00–19:00", st: "Mantaha–Labohlano: 07:00–19:00", fr: "Lundi–Vendredi: 07:00–19:00", de: "Montag–Freitag: 07:00–19:00", pt: "Segunda–Sexta: 07:00–19:00", es: "Lunes–Viernes: 07:00–19:00", zh: "周一至周五: 07:00–19:00" },
  "contact.sat": { en: "Saturday: 12:00–17:00", af: "Saterdag: 12:00–17:00", zu: "Mgqibelo: 12:00–17:00", xh: "Mgqibelo: 12:00–17:00", st: "Moqebelo: 12:00–17:00", fr: "Samedi: 12:00–17:00", de: "Samstag: 12:00–17:00", pt: "Sábado: 12:00–17:00", es: "Sábado: 12:00–17:00", zh: "周六: 12:00–17:00" },
  "contact.sun": { en: "Sunday: Closed", af: "Sondag: Gesluit", zu: "Isonto: Kuvaliwe", xh: "Cawa: Kuvaliwe", st: "Sontaha: Koetswe", fr: "Dimanche: Fermé", de: "Sonntag: Geschlossen", pt: "Domingo: Fechado", es: "Domingo: Cerrado", zh: "周日: 已关闭" },
  "contact.sendMessage": { en: "Send Message", af: "Stuur Boodskap", zu: "Thumela Umlayezo", xh: "Thumela Umyalezo", st: "Romela Molaetsa", fr: "Envoyer le Message", de: "Nachricht Senden", pt: "Enviar Mensagem", es: "Enviar Mensaje", zh: "发送消息" },
  "contact.sendUs": { en: "Send Us a Message", af: "Stuur Vir Ons 'n Boodskap", zu: "Sithumelele Umlayezo", xh: "Sithumelele Umyalezo", st: "Re Romele Molaetsa", fr: "Envoyez-nous un Message", de: "Senden Sie Uns eine Nachricht", pt: "Envie-nos uma Mensagem", es: "Envíanos un Mensaje", zh: "给我们发消息" },
  "contact.messageSent": { en: "Message sent!", af: "Boodskap gestuur!", zu: "Umlayezo uthunyelwe!", xh: "Umyalezo uthunyelwe!", st: "Molaetsa o rometswe!", fr: "Message envoyé!", de: "Nachricht gesendet!", pt: "Mensagem enviada!", es: "¡Mensaje enviado!", zh: "消息已发送！" },
  "contact.inTouch": { en: "We'll be in touch within 24 hours.", af: "Ons sal binne 24 uur kontak maak.", zu: "Sizokuxhumana phakathi namahora angu-24.", xh: "Siza kuqhagamshelana ngaphakathi kweeyure ezingama-24.", st: "Re tla ikopanya ka hare ho dihora tse 24.", fr: "Nous vous contacterons sous 24 heures.", de: "Wir melden uns innerhalb von 24 Stunden.", pt: "Entraremos em contacto dentro de 24 horas.", es: "Nos pondremos en contacto en 24 horas.", zh: "我们将在24小时内与您联系。" },

  // Form fields
  "form.firstName": { en: "First Name", af: "Voornaam", zu: "Igama", xh: "Igama", st: "Lebitso", fr: "Prénom", de: "Vorname", pt: "Primeiro Nome", es: "Nombre", zh: "名字" },
  "form.lastName": { en: "Last Name", af: "Van", zu: "Isibongo", xh: "Ifani", st: "Fane", fr: "Nom de Famille", de: "Nachname", pt: "Apelido", es: "Apellido", zh: "姓氏" },
  "form.email": { en: "Email Address", af: "E-posadres", zu: "Ikheli le-imeyili", xh: "Idilesi ye-imeyile", st: "Aterese ya Imeile", fr: "Adresse E-mail", de: "E-Mail-Adresse", pt: "Endereço de E-mail", es: "Dirección de Correo", zh: "电子邮件地址" },
  "form.phone": { en: "Phone Number", af: "Telefoonnommer", zu: "Inombolo yocingo", xh: "Inombolo yefowuni", st: "Nomoro ya Mohala", fr: "Numéro de Téléphone", de: "Telefonnummer", pt: "Número de Telefone", es: "Número de Teléfono", zh: "电话号码" },
  "form.interest": { en: "I'm Interested In", af: "Ek Stel Belang In", zu: "Ngithanda", xh: "Ndinomdla Ku", st: "Ke Kgothaletse", fr: "Je Suis Intéressé Par", de: "Ich Interessiere Mich Für", pt: "Estou Interessado Em", es: "Estoy Interesado En", zh: "我感兴趣的" },
  "form.tellUs": { en: "Tell Us About Your Project", af: "Vertel Ons Van U Projek", zu: "Sitshele Ngephrojekthi Yakho", xh: "Sixelele Ngephrojekthi Yakho", st: "Re Bolelle ka Projeke ya Hao", fr: "Parlez-nous de Votre Projet", de: "Erzählen Sie uns von Ihrem Projekt", pt: "Fale-nos Sobre o Seu Projeto", es: "Cuéntanos Sobre Tu Proyecto", zh: "告诉我们您的项目" },
  "form.select": { en: "Select an option...", af: "Kies 'n opsie...", zu: "Khetha inketho...", xh: "Khetha ukhetho...", st: "Khetha khetho...", fr: "Sélectionnez une option...", de: "Option wählen...", pt: "Selecione uma opção...", es: "Selecciona una opción...", zh: "选择一个选项..." },
  "form.sending": { en: "Sending...", af: "Stuur...", zu: "Kuthunyelwa...", xh: "Kuthunyelwa...", st: "Ho romelloa...", fr: "Envoi...", de: "Wird gesendet...", pt: "Enviando...", es: "Enviando...", zh: "发送中..." },
  "form.selectedPlan": { en: "You selected:", af: "U het gekies:", zu: "Ukhethe:", xh: "Ukhethe:", st: "U khethile:", fr: "Vous avez sélectionné:", de: "Sie haben gewählt:", pt: "Você selecionou:", es: "Seleccionaste:", zh: "您选择了：" },
  "form.plan": { en: "Plan", af: "Plan", zu: "Uhlelo", xh: "Isicwangciso", st: "Moralo", fr: "Forfait", de: "Plan", pt: "Plano", es: "Plan", zh: "计划" },

  // Footer
  "footer.company": { en: "Company", af: "Maatskappy", zu: "Inkampani", xh: "Inkampani", st: "K'hamphani", fr: "Entreprise", de: "Unternehmen", pt: "Empresa", es: "Empresa", zh: "公司" },
  "footer.services": { en: "Services", af: "Dienste", zu: "Izinsiza", xh: "Iinkonzo", st: "Ditshebeletso", fr: "Services", de: "Dienstleistungen", pt: "Serviços", es: "Servicios", zh: "服务" },
  "footer.contact": { en: "Contact", af: "Kontak", zu: "Xhumana", xh: "Qhagamshelana", st: "Ikopanye", fr: "Contact", de: "Kontakt", pt: "Contacto", es: "Contacto", zh: "联系" },
  "footer.tagline": { en: "Modern web design for South African businesses that want to stand out and grow online. Packages from R5,500.", af: "Moderne webontwerp vir Suid-Afrikaanse besighede wat wil uitstaan en aanlyn groei. Pakkette vanaf R5,500.", zu: "Ukwakhiwa kwamawebhusayithi asamodern amabhizinisi aseNingizimu Afrika afuna ukugqama nokukhula ku-inthanethi. Amaphakheji kusuka ku-R5,500.", xh: "Uyilo lwewebhu zanamhlanje zamashishini aseMzantsi Afrika afuna ukugqama nokukhula kwi-intanethi. Iimpahla ukusuka kwi-R5,500.", st: "Moralo oa marang-rang oa sejoale-joale bakeng sa likgwebo tsa Afrika Borwa tse batlang ho ikhetholla le ho hola inthaneteng. Dipakete ho tloha ho R5,500.", fr: "Conception web moderne pour les entreprises sud-africaines qui veulent se démarquer et se développer en ligne. Forfaits à partir de R5 500.", de: "Modernes Webdesign für südafrikanische Unternehmen, die sich abheben und online wachsen wollen. Pakete ab R5.500.", pt: "Design web moderno para empresas sul-africanas que querem se destacar e crescer online. Pacotes a partir de R5.500.", es: "Diseño web moderno para empresas sudafricanas que quieren destacar y crecer online. Paquetes desde R5.500.", zh: "为希望脱颖而出并在线成长的南非企业提供现代网页设计。套餐起价R5,500。" },
  "footer.websiteDesign": { en: "Website Design", af: "Webwerf Ontwerp", zu: "Ukwakhiwa Kwewebhusayithi", xh: "Uyilo Lwewebhsayithi", st: "Moralo oa Saete", fr: "Conception Web", de: "Webdesign", pt: "Design Web", es: "Diseño Web", zh: "网站设计" },
  "footer.monthlyMaintenance": { en: "Monthly Maintenance", af: "Maandelikse Onderhoud", zu: "Ukugcina Kwenyanga", xh: "Ukulondoloza Kwenyanga", st: "Tlhokomelo ea Khoeli", fr: "Maintenance Mensuelle", de: "Monatliche Wartung", pt: "Manutenção Mensal", es: "Mantenimiento Mensual", zh: "月度维护" },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<LangCode>(() => {
    return (localStorage.getItem("preferred-lang") as LangCode) || "en";
  });

  const setLang = useCallback((code: LangCode) => {
    setLangState(code);
    localStorage.setItem("preferred-lang", code);
  }, []);

  const t = useCallback(
    (key: string): string => {
      const entry = T[key];
      if (!entry) return key;
      return entry[lang] || entry.en || key;
    },
    [lang],
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
